server:
  port: 9001

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5433/authdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
