server:
  port: 9003

spring:
  application:
    name: course-service

  datasource:
    url: jdbc:postgresql://localhost:5433/coursedb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      uri: mongodb://localhost:27018/course_db

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
