server:
  port: 9005

spring:
  application:
    name: quiz-service

  datasource:
    url: jdbc:postgresql://localhost:5433/quizdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      uri: mongodb://localhost:27018/quiz_db

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
